In [27]:
# Mini Project: Food Delivery Delay Prediction Using Machine Learning - Random Forest Model

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

data = pd.read_csv("Zomato Dataset.csv")
df1 = pd.DataFrame(data)
df = df1.copy()
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [28]:
# EDA Preprocessing Method

print(df.head())
print(df.shape)
print(df.info())
print(df.isnull().sum())
print(df.duplicated().sum())

#df = df2.drop(columns=["Order_Date","Weather_conditions","Festival","City","Type_of_order","Type_of_vehicle"])

       ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  0xcdcd      DEHRES17DEL01                 36.0                      4.2
1  0xd987      KOCRES16DEL01                 21.0                      4.7
2  0x2784     PUNERES13DEL03                 23.0                      4.7
3  0xc8b6     LUDHRES15DEL02                 34.0                      4.3
4  0xdb64      KNPRES14DEL02                 24.0                      4.7

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            30.327968             78.046106                   30.397968
1            10.003064             76.307589                   10.043064
2            18.562450             73.916619                   18.652450
3            30.899584             75.809346                   30.919584
4            26.463504             80.372929                   26.593504

   Delivery_location_longitude  Order_Date Time_Orderd Time_Order_picked  \
0                    78.116106  12-02-2022       21:55             22:10
1                    76.347589  13-02-2022       14:55             15:05
2                    74.006619  04-03-2022       17:30             17:40
3                    75.829346  13-02-2022       09:20             09:30
4                    80.502929  14-02-2022       19:50             20:05

  Weather_conditions Road_traffic_density  Vehicle_condition Type_of_order  \
0                Fog                  Jam                  2         Snack
1             Stormy                 High                  1          Meal
2         Sandstorms               Medium                  1        Drinks
3         Sandstorms                  Low                  0        Buffet
4                Fog                  Jam                  1         Snack

  Type_of_vehicle  multiple_deliveries Festival           City  \
0      motorcycle                  3.0       No  Metropolitian
1      motorcycle                  1.0       No  Metropolitian
2         scooter                  1.0       No  Metropolitian
3      motorcycle                  0.0       No  Metropolitian
4         scooter                  1.0       No  Metropolitian

   Time_taken (min)
0                46
1                23
2                21
3                20
4                41
(45584, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  object
 1   Delivery_person_ID           45584 non-null  object
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  object
 9   Time_Orderd                  43853 non-null  object
 10  Time_Order_picked            45584 non-null  object
 11  Weather_conditions           44968 non-null  object
 12  Road_traffic_density         44983 non-null  object
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  object
 15  Type_of_vehicle              45584 non-null  object
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  object
 18  City                         44384 non-null  object
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), object(11)
memory usage: 7.0+ MB
None
ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64
0

In [29]:
pd.DataFrame({"Find Null Values":df.isnull().sum()})

                             Find Null Values
ID                                          0
Delivery_person_ID                          0
Delivery_person_Age                      1854
Delivery_person_Ratings                  1908
Restaurant_latitude                         0
Restaurant_longitude                        0
Delivery_location_latitude                  0
Delivery_location_longitude                 0
Order_Date                                  0
Time_Orderd                              1731
Time_Order_picked                           0
Weather_conditions                        616
Road_traffic_density                      601
Vehicle_condition                           0
Type_of_order                               0
Type_of_vehicle                             0
multiple_deliveries                       993
Festival                                  228
City                                     1200
Time_taken (min)                            0

In [30]:
df.dropna(subset=["Time_Orderd"],inplace=True)
print(df["Festival"].value_counts(dropna=False))
print(df['City'].value_counts(dropna=False))
df.isnull().sum()

Festival
No     42777
Yes      857
NaN      219
Name: count, dtype: int64
City
Metropolitian    32796
Urban             9757
NaN               1144
Semi-Urban         156
Name: count, dtype: int64

ID                                0
Delivery_person_ID                0
Delivery_person_Age             214
Delivery_person_Ratings         268
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             943
Festival                        219
City                           1144
Time_taken (min)                  0
dtype: int64

In [31]:
# Finding NaN Values

df['City']=df['City'].replace('NaN', np.nan)
df['Festival']=df['Festival'].replace('NaN', np.nan)
df['City']=df['City'].fillna(df['City'].mode())
df['Festival']=df['Festival'].fillna(df['Festival'].mode().iloc[0])
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age             214
Delivery_person_Ratings         268
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             943
Festival                          0
City                           1144
Time_taken (min)                  0
dtype: int64

In [32]:
# Replacing NaN values By Mean Median Mode

df["Delivery_person_Age"]= df["Delivery_person_Age"].fillna(df["Delivery_person_Age"].mean())
df["Delivery_person_Ratings"]= df["Delivery_person_Ratings"].fillna(df["Delivery_person_Ratings"].mean())
df["multiple_deliveries"]= df["multiple_deliveries"].fillna(df["multiple_deliveries"].mean())
print("Delivery_person_Age Nan Values     :",df["Delivery_person_Age"].isnull().sum())
print("Delivery_person_Ratings Nan Values :",df["Delivery_person_Ratings"].isnull().sum())
print("multiple_deliveries Nan Values     :",df["multiple_deliveries"].isnull().sum())

Delivery_person_Age Nan Values     : 0
Delivery_person_Ratings Nan Values : 0
multiple_deliveries Nan Values     : 0

In [33]:
# Categorical columns into Numerical columns

numerical_cols=df[['Delivery_person_Age','Delivery_person_Ratings','Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude','Delivery_location_longitude',	'Vehicle_condition','multiple_deliveries','Time_taken (min)']]
print(numerical_cols.corr())

df['delayed']=None
print(df.isnull().sum())

                             Delivery_person_Age  Delivery_person_Ratings  \
Delivery_person_Age                     1.000000                -0.117517
Delivery_person_Ratings                -0.117517                 1.000000
Restaurant_latitude                     0.001400                -0.012051
Restaurant_longitude                    0.000077                -0.013448
Delivery_location_latitude              0.002448                -0.013505
Delivery_location_longitude             0.000074                -0.013635
Vehicle_condition                      -0.001936                 0.048777
multiple_deliveries                     0.116404                -0.125100
Time_taken (min)                        0.303037                -0.359836

                             Restaurant_latitude  Restaurant_longitude  \
Delivery_person_Age                     0.001400              0.000077
Delivery_person_Ratings                -0.012051             -0.013448
Restaurant_latitude                     1.000000              0.650109
Restaurant_longitude                    0.650109              1.000000
Delivery_location_latitude              0.935340              0.690755
Delivery_location_longitude             0.650162              0.999998
Vehicle_condition                      -0.001751             -0.003807
multiple_deliveries                     0.008012              0.004343
Time_taken (min)                        0.015243              0.008073

                             Delivery_location_latitude  \
Delivery_person_Age                            0.002448
Delivery_person_Ratings                       -0.013505
Restaurant_latitude                            0.935340
Restaurant_longitude                           0.690755
Delivery_location_latitude                     1.000000
Delivery_location_longitude                    0.690817
Vehicle_condition                             -0.000711
multiple_deliveries                            0.008920
Time_taken (min)                               0.014815

                             Delivery_location_longitude  Vehicle_condition  \
Delivery_person_Age                             0.000074          -0.001936
Delivery_person_Ratings                        -0.013635           0.048777
Restaurant_latitude                             0.650162          -0.001751
Restaurant_longitude                            0.999998          -0.003807
Delivery_location_latitude                      0.690817          -0.000711
Delivery_location_longitude                     1.000000          -0.003794
Vehicle_condition                              -0.003794           1.000000
multiple_deliveries                             0.004561          -0.101409
Time_taken (min)                                0.008631          -0.243176

                             multiple_deliveries  Time_taken (min)
Delivery_person_Age                     0.116404          0.303037
Delivery_person_Ratings                -0.125100         -0.359836
Restaurant_latitude                     0.008012          0.015243
Restaurant_longitude                    0.004343          0.008073
Delivery_location_latitude              0.008920          0.014815
Delivery_location_longitude             0.004561          0.008631
Vehicle_condition                      -0.101409         -0.243176
multiple_deliveries                     1.000000          0.383721
Time_taken (min)                        0.383721          1.000000
ID                                 0
Delivery_person_ID                 0
Delivery_person_Age                0
Delivery_person_Ratings            0
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                        0
Time_Order_picked                  0
Weather_conditions                 0
Road_traffic_density               0
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries                0
Festival                           0
City                            1144
Time_taken (min)                   0
delayed                        43853
dtype: int64

In [34]:
# creating New Columns in a Datasets

df['delayed'] = (df['Time_taken (min)'] >=30).astype(int)
print(df["delayed"])

0        1
1        0
2        0
3        0
4        1
        ..
45579    1
45580    1
45581    0
45582    0
45583    1
Name: delayed, Length: 43853, dtype: int64

In [36]:
# Add Features column in the Dataset

feature_cols = ['Delivery_person_Age','Delivery_person_Ratings',
    'Weather_conditions','Road_traffic_density','Vehicle_condition',
    'Type_of_vehicle','multiple_deliveries','Festival','City'
]
df_clean = df[feature_cols + ['delayed']].dropna()
print(df_clean.head(10))

df_encoded = pd.get_dummies(df_clean,drop_first=True)
print(df_encoded.head(5))

   Delivery_person_Age  Delivery_person_Ratings Weather_conditions  \
0                 36.0                      4.2                Fog
1                 21.0                      4.7             Stormy
2                 23.0                      4.7         Sandstorms
3                 34.0                      4.3         Sandstorms
4                 24.0                      4.7                Fog
5                 29.0                      4.5         Sandstorms
6                 35.0                      4.0              Windy
7                 33.0                      4.2         Sandstorms
8                 34.0                      4.9             Cloudy
9                 21.0                      4.7              Windy

  Road_traffic_density  Vehicle_condition   Type_of_vehicle  \
0                  Jam                  2        motorcycle
1                 High                  1        motorcycle
2               Medium                  1           scooter
3                  Low                  0        motorcycle
4                  Jam                  1           scooter
5                  Jam                  2  electric_scooter
6                 High                  1           scooter
7                  Jam                  2        motorcycle
8                  Jam                  0        motorcycle
9                  Jam                  0        motorcycle

   multiple_deliveries Festival           City  delayed
0             3.000000       No  Metropolitian        1
1             1.000000       No  Metropolitian        0
2             1.000000       No  Metropolitian        0
3             0.000000       No  Metropolitian        0
4             1.000000       No  Metropolitian        1
5             1.000000       No  Metropolitian        0
6             1.000000       No  Metropolitian        1
7             1.000000       No  Metropolitian        1
8             0.744092       No  Metropolitian        1
9             1.000000       No          Urban        0
   Delivery_person_Age  Delivery_person_Ratings  Vehicle_condition  \
0                 36.0                      4.2                  2
1                 21.0                      4.7                  1
2                 23.0                      4.7                  1
3                 34.0                      4.3                  0
4                 24.0                      4.7                  1

   multiple_deliveries  delayed  Weather_conditions_Fog  \
0                  3.0        1                    True
1                  1.0        0                   False
2                  1.0        0                   False
3                  0.0        0                   False
4                  1.0        1                    True

   Weather_conditions_Sandstorms  Weather_conditions_Stormy  \
0                          False                      False
1                          False                       True
2                           True                      False
3                           True                      False
4                          False                      False

   Weather_conditions_Sunny  Weather_conditions_Windy  \
0                     False                     False
1                     False                     False
2                     False                     False
3                     False                     False
4                     False                     False

   Road_traffic_density_Jam  Road_traffic_density_Low  \
0                      True                     False
1                     False                     False
2                     False                     False
3                     False                      True
4                      True                     False

   Road_traffic_density_Medium  Type_of_vehicle_motorcycle  \
0                        False                        True
1                        False                        True
2                         True                       False
3                        False                        True
4                        False                       False

   Type_of_vehicle_scooter  Festival_Yes  City_Semi-Urban  City_Urban
0                    False         False            False       False
1                    False         False            False       False
2                     True         False            False       False
3                    False         False            False       False
4                     True         False            False       False

In [52]:
# Total Columns Name

print(df_encoded.columns)

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Vehicle_condition',
       'multiple_deliveries', 'delayed', 'Weather_conditions_Fog',
       'Weather_conditions_Sandstorms', 'Weather_conditions_Stormy',
       'Weather_conditions_Sunny', 'Weather_conditions_Windy',
       'Road_traffic_density_Jam', 'Road_traffic_density_Low',
       'Road_traffic_density_Medium', 'Type_of_vehicle_motorcycle',
       'Type_of_vehicle_scooter', 'Festival_Yes', 'City_Semi-Urban',
       'City_Urban'],
      dtype='object')

In [40]:
# Model Features Spliting

X = df_encoded[['Delivery_person_Age', 'Delivery_person_Ratings', 'Vehicle_condition',
       'multiple_deliveries', 'Weather_conditions_Fog',
       'Weather_conditions_Sandstorms', 'Weather_conditions_Stormy',
       'Weather_conditions_Sunny', 'Weather_conditions_Windy',
       'Road_traffic_density_Jam', 'Road_traffic_density_Low',
       'Road_traffic_density_Medium', 'Type_of_vehicle_motorcycle',
       'Type_of_vehicle_scooter', 'Festival_Yes', 'City_Semi-Urban',
       'City_Urban']]
y = df_encoded["delayed"]

In [41]:
# Model Training

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Predicting Values

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)

In [45]:
# Data Featuers Encoding & Predict Outputs

columns = pd.DataFrame({'Input Features': y_test.values, 'Predicted Features': y_pred})
columns['Actual Status'] = columns['Input Features'].map({0: 'Not Delayed', 1: 'Delayed'})
columns['Predicted Status'] = columns['Predicted Features'].map({0: 'Not Delayed', 1: 'Delayed'})

print(columns)

      Input Features  Predicted Features Actual Status Predicted Status
0                  0                   0   Not Delayed      Not Delayed
1                  1                   1       Delayed          Delayed
2                  0                   1   Not Delayed          Delayed
3                  1                   1       Delayed          Delayed
4                  0                   0   Not Delayed      Not Delayed
...              ...                 ...           ...              ...
8537               1                   0       Delayed      Not Delayed
8538               0                   0   Not Delayed      Not Delayed
8539               1                   1       Delayed          Delayed
8540               1                   1       Delayed          Delayed
8541               0                   0   Not Delayed      Not Delayed

[8542 rows x 4 columns]

In [51]:
# Model Accuracy Rate
print(f"Model Accuracy Rate : {accuracy*100:.2f}")
print("Classification_report : \n",classification_report(y_test,y_pred))
print("Confusion_matrix : \n",confusion_matrix(y_test,y_pred))

Model Accuracy Rate : 87.27
Classification_report :
               precision    recall  f1-score   support

           0       0.89      0.92      0.91      5688
           1       0.83      0.79      0.80      2854

    accuracy                           0.87      8542
   macro avg       0.86      0.85      0.86      8542
weighted avg       0.87      0.87      0.87      8542

Confusion_matrix :
 [[5214  474]
 [ 613 2241]]